lastupdatecheck: 0
recentrepos:
- /home/cadra/.dotfiles
- /home/cadra/Documents/repos/SE370-2023-Team3-dnd-creation-app
- /home/cadra/Documents/Programming
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
ignorewhitespaceindiffview: false
